version: '3.8'
services:
  php_apache:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8434:8434
    volumes:
      - ./my-datavolume:/var/www/html
    networks:
      - company_network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: sql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: CTF2
      MYSQL_USER: USER
      MYSQL_PASSWORD: CTFPASSWORD
    ports:
      - "20678:20678"
    volumes:
      - ./my-datavolume:/var/lib/mysql  
    networks:
      - company_network

  redis:
    image: redis:7.2.1
    container_name: redis
    restart: always
    ports:
      - 20616:20616
    networks:
      - company_network      

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 23967:8434
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=20678
    networks:
      - company_network        

networks:
  company_network: